/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import handlers.FCHandler;
import javax.swing.JOptionPane;

/**
 *
 * @author Patrick
 */
public class AddFlashCardGUI extends javax.swing.JDialog {

    private FCHandler fCHandler;

    /**
     * Creates new form AddFlashCardGUI
     */
    public AddFlashCardGUI(java.awt.Frame parent, boolean modal, FCHandler fCHandler) {
        super(parent, modal);
        this.fCHandler = fCHandler;
        initComponents();
    }

    public boolean areFieldsNull() {
        if (textFieldEnglish.getText().equalsIgnoreCase("") || textFieldRomaji.getText().equalsIgnoreCase("") || textFieldHiragana.getText().equalsIgnoreCase("") || textFieldKanji.getText().equalsIgnoreCase("")) {
            return true;
        }
        return false;
    }
    
    public void reset(){
        textFieldEnglish.setText("");
        textFieldRomaji.setText("");
        textFieldHiragana.setText("");
        textFieldKanji.setText("");
    }
    public void start(){
        setLocationRelativeTo(null);
        reset();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonAdd = new javax.swing.JButton();
        textFieldEnglish = new javax.swing.JTextField();
        textFieldRomaji = new javax.swing.JTextField();
        textFieldHiragana = new javax.swing.JTextField();
        textFieldKanji = new javax.swing.JTextField();
        labelEnglish = new javax.swing.JLabel();
        labelRomaji = new javax.swing.JLabel();
        labelHiragana = new javax.swing.JLabel();
        labelKanji = new javax.swing.JLabel();
        buttonReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonAdd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        textFieldEnglish.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textFieldEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEnglishActionPerformed(evt);
            }
        });

        textFieldRomaji.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        textFieldHiragana.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textFieldHiragana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldHiraganaActionPerformed(evt);
            }
        });

        textFieldKanji.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        labelEnglish.setText("English");

        labelRomaji.setText("Romaji");

        labelHiragana.setText("Kana");

        labelKanji.setText("Kanji");

        buttonReturn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonReturn.setText("Return");
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEnglish)
                            .addComponent(labelRomaji)
                            .addComponent(labelHiragana)
                            .addComponent(labelKanji))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldEnglish)
                            .addComponent(textFieldRomaji)
                            .addComponent(textFieldHiragana)
                            .addComponent(textFieldKanji)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 145, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(buttonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEnglish))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldRomaji, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRomaji))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldHiragana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHiragana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldKanji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKanji))
                .addGap(18, 18, 18)
                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEnglishActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        if (areFieldsNull()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled.", "Något har gått fel", JOptionPane.ERROR_MESSAGE);
        } else {
            fCHandler.create(textFieldEnglish.getText(), textFieldRomaji.getText(), textFieldHiragana.getText(), textFieldKanji.getText());
            reset();
        }
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        reset();
        this.dispose();
    }//GEN-LAST:event_buttonReturnActionPerformed

    private void textFieldHiraganaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldHiraganaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldHiraganaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddFlashCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddFlashCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddFlashCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddFlashCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                AddFlashCardGUI dialog = new AddFlashCardGUI(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonReturn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelEnglish;
    private javax.swing.JLabel labelHiragana;
    private javax.swing.JLabel labelKanji;
    private javax.swing.JLabel labelRomaji;
    private javax.swing.JTextField textFieldEnglish;
    private javax.swing.JTextField textFieldHiragana;
    private javax.swing.JTextField textFieldKanji;
    private javax.swing.JTextField textFieldRomaji;
    // End of variables declaration//GEN-END:variables
}
