/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import handlers.FCHandler;
import java.awt.TextField;
import model.FlashCard;

/**
 *
 * @author Patrick
 */
public class FlashCards extends javax.swing.JDialog {

    private FCHandler fCHandler;
    FlashCard f;
    private boolean done = false;
    private int scoreCorrect = 0;
    private int scoreWrong = 0;
    private String user;

    /**
     * Creates new form FlashCards
     */
    public FlashCards(java.awt.Frame parent, boolean modal, FCHandler fCHandler) {
        super(parent, modal);
        initComponents();
        this.fCHandler = fCHandler;
        setLocationRelativeTo(null);

    }

    public FlashCards(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

    }

    public void nextCard() {
        f = fCHandler.nextCardEWORD();
        if (f != null) {
            eWordLabel.setText(f.geteWord());
            romajiLabel.setText("????");
            hiraganaLabel.setText("????");
            kanjiLabel.setText("?");
            hideCWbuttons();
        } else {
            //To do when everything is answered
            done();

        }
    }

    public void done() {
        buttonWrong.setText("Exit");
        buttonCorrect.setText("Return");
        done = true;
        showCWbuttons();
    }

    public void start(String user) {
        this.user = user;
        fCHandler.loadFlashCards(user);
        reset();
        nextCard();
        setVisible(true);
    }

    public void reset() {
        buttonCorrect.setText("Correct");
        buttonWrong.setText("Wrong");
        done = false;
        labelCorrectScore.setText("0");
        labelWrongScore.setText("0");
        scoreCorrect = 0;
        scoreWrong = 0;
    }

    public void showAnswer() {
        romajiLabel.setText(f.getRomaji());
        hiraganaLabel.setText(f.getHiragana());
        kanjiLabel.setText(f.getKanji());
        showCWbuttons();
    }

    public void hideCWbuttons() {
        buttonCorrect.setVisible(false);
        buttonWrong.setVisible(false);
        buttonAnswered.setVisible(true);

    }

    public void showCWbuttons() {
        buttonCorrect.setVisible(true);
        buttonWrong.setVisible(true);
        buttonAnswered.setVisible(false);
    }

    public void ScoreCorrect() {
        scoreCorrect++;
        labelCorrectScore.setText(Integer.toString(scoreCorrect));
    }

    public void ScoreWrong() {
        scoreWrong++;
        labelWrongScore.setText(Integer.toString(scoreWrong));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        eWordLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        romajiLabel = new javax.swing.JLabel();
        kanjiLabel = new javax.swing.JLabel();
        hiraganaLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        buttonAnswered = new javax.swing.JButton();
        buttonCorrect = new javax.swing.JButton();
        buttonWrong = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 126), new java.awt.Dimension(0, 126), new java.awt.Dimension(32767, 126));
        jPanel4 = new javax.swing.JPanel();
        labelCorrect = new javax.swing.JLabel();
        labelCorrectScore = new javax.swing.JLabel();
        labelWrong = new javax.swing.JLabel();
        labelWrongScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Flash Card");
        setMaximumSize(new java.awt.Dimension(455, 350));
        setMinimumSize(new java.awt.Dimension(455, 350));
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Arrow.jpg"))); // NOI18N

        eWordLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eWordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        eWordLabel.setText("English");

        romajiLabel.setFont(new java.awt.Font("MS Gothic", 0, 18)); // NOI18N
        romajiLabel.setText("Romaji");

        kanjiLabel.setFont(new java.awt.Font("MS Gothic", 0, 18)); // NOI18N
        kanjiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kanjiLabel.setText("Kanji");

        hiraganaLabel.setFont(new java.awt.Font("MS Gothic", 0, 18)); // NOI18N
        hiraganaLabel.setText("Kana");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(romajiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hiraganaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kanjiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kanjiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(romajiLabel)
                    .addComponent(hiraganaLabel))
                .addContainerGap())
        );

        buttonAnswered.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonAnswered.setText("Answered");
        buttonAnswered.setFocusable(false);
        buttonAnswered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnsweredActionPerformed(evt);
            }
        });

        buttonCorrect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCorrect.setText("Correct");
        buttonCorrect.setFocusable(false);
        buttonCorrect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCorrectActionPerformed(evt);
            }
        });

        buttonWrong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonWrong.setText("Wrong");
        buttonWrong.setFocusable(false);
        buttonWrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWrongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(buttonAnswered, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(buttonWrong, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonAnswered, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonWrong, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        labelCorrect.setText("Correct");

        labelCorrectScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCorrectScore.setText("0");
        labelCorrectScore.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelWrong.setText("Wrong");

        labelWrongScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWrongScore.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelCorrect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCorrectScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelWrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelWrongScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCorrect)
                    .addComponent(labelWrong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCorrectScore)
                    .addComponent(labelWrongScore))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(eWordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(eWordLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonWrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWrongActionPerformed
        if (done) {
            System.exit(0);
        } else {
            fCHandler.wrong(f, 0, user);
            ScoreWrong();
            nextCard();
        }
    }//GEN-LAST:event_buttonWrongActionPerformed

    private void buttonCorrectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCorrectActionPerformed
        if (done) {
            this.dispose();
        } else {
            fCHandler.correct(f, 0, user);
            ScoreCorrect();
            nextCard();
        }
    }//GEN-LAST:event_buttonCorrectActionPerformed

    private void buttonAnsweredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnsweredActionPerformed
        showAnswer();
    }//GEN-LAST:event_buttonAnsweredActionPerformed
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FlashCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FlashCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FlashCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FlashCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FlashCards dialog = new FlashCards(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnswered;
    private javax.swing.JButton buttonCorrect;
    private javax.swing.JButton buttonWrong;
    private javax.swing.JLabel eWordLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel hiraganaLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel kanjiLabel;
    private javax.swing.JLabel labelCorrect;
    private javax.swing.JLabel labelCorrectScore;
    private javax.swing.JLabel labelWrong;
    private javax.swing.JLabel labelWrongScore;
    private javax.swing.JLabel romajiLabel;
    // End of variables declaration//GEN-END:variables
}
